[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/functions/discord/authorize"
  to = "/.netlify/functions/discord-auth"
  status = 200

[build.environment]
  NODE_VERSION = "18"
